import { Op, Transaction, WhereOptions } from "sequelize";
import { Post } from "@models/post.model";
import { Media, MediaAttributes, MediaCreationAttributes } from "./media.model";
import {
  ALLOWED_DOCUMENT_MIME_TYPES,
  ALLOWED_IMAGE_MIME_TYPES,
  MediaKind,
} from "./media.dto";

// Enough to tell the admin where the asset is used without building an
// unbounded response for an asset reused across a hundred posts.
const MAX_REPORTED_REFERENCES = 10;

// A media URL is generated by us, not user input, but it still reaches a LIKE
// pattern — so neutralise the wildcards rather than trusting that forever.
function escapeLike(value: string): string {
  return value.replace(/[\\%_]/g, "\\$&");
}

export class MediaRepository {
  async create(payload: MediaCreationAttributes): Promise<Media> {
    return Media.create(payload);
  }

  private kindWhere(kind?: MediaKind): WhereOptions<MediaAttributes> | undefined {
    if (kind === undefined) {
      return undefined;
    }

    return {
      mimeType: {
        [Op.in]:
          kind === "document"
            ? [...ALLOWED_DOCUMENT_MIME_TYPES]
            : [...ALLOWED_IMAGE_MIME_TYPES],
      },
    };
  }

  async findAll(kind?: MediaKind): Promise<Media[]> {
    return Media.findAll({
      where: this.kindWhere(kind),
      order: [["createdAt", "DESC"]],
    });
  }

  // Paginated listing for the media library and picker. The unpaginated
  // findAll above returned the entire library in one response, which grows
  // without bound as the blog accumulates images.
  async findPaginated(
    page: number,
    limit: number,
    kind?: MediaKind,
  ): Promise<{ rows: Media[]; count: number }> {
    return Media.findAndCountAll({
      where: this.kindWhere(kind),
      order: [["createdAt", "DESC"]],
      limit,
      offset: (page - 1) * limit,
    });
  }

  async findById(id: string, transaction?: Transaction): Promise<Media | null> {
    return Media.findByPk(id, { transaction });
  }

  /**
   * Every post that would break if this media asset disappeared.
   *
   * Two kinds of reference exist, and only one of them is a foreign key:
   *
   *  - `posts.featured_image_id` — a real FK, tracked by the schema.
   *  - Inline body images and PDF chips — NOT tracked. The editor embeds the
   *    asset's URL directly into the post's HTML, so nothing in the schema
   *    connects the two. Matching the stored URL against the body is what makes
   *    those references visible at all; without it, deleting an image used
   *    inside an article silently leaves a broken image in published content.
   *
   * Soft-deleted posts are excluded (the model is paranoid, so the default
   * scope already does that) — a post in the bin should not block a cleanup.
   */
  async findReferencingPosts(
    media: Media,
  ): Promise<{ id: string; title: string }[]> {
    const rows = await Post.findAll({
      attributes: ["id", "title"],
      where: {
        [Op.or]: [
          { featuredImageId: media.id },
          { content: { [Op.like]: `%${escapeLike(media.url)}%` } },
          { pdfUrl: media.url },
        ],
      },
      limit: MAX_REPORTED_REFERENCES,
      order: [["updatedAt", "DESC"]],
    });

    return rows.map((row) => ({ id: row.id, title: row.title }));
  }

  async softDeleteById(id: string): Promise<boolean> {
    const deletedCount = await Media.destroy({ where: { id } });
    return deletedCount > 0;
  }
}

const mediaRepository = new MediaRepository();

export default mediaRepository;
